#!/bin/sh

OF=transition-$(date +%Y%m%d).db

pg_dump --username=cayuse rubyorder_production > $OF;
dropdb --username=cayuse rubyorder_development;
createdb --username=cayuse rubyorder_development;
psql --username=cayuse rubyorder_development -f $OF;
cp $OF db.back;
echo "Don't Forget to Copy the db file $OF."
#svn commit -m "db store";


